# Generated by Django 3.2.8 on 2021-10-11 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='server_address',
        ),
        migrations.AddField(
            model_name='session',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 15, 11, 5, 71741)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='public_key',
            field=models.BinaryField(default=b'', max_length=64),
            preserve_default=False,
        ),
    ]
