# Generated by Django 3.2.8 on 2021-10-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0002_auto_20211011_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='public_key',
            field=models.BinaryField(max_length=255),
        ),
    ]
