# Generated by Django 3.2.7 on 2021-10-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.BinaryField(default=None, max_length=16, null=True, unique=True),
        ),
    ]
