# Generated by Django 3.2.8 on 2021-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.BinaryField(default=None, max_length=32, null=True, unique=True),
        ),
    ]
