# Generated by Django 3.2.8 on 2021-10-13 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0004_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 17, 2, 44, 127408, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
